images_folder: "/images"

postgres:
  user: postgres
  password: postgres
  host: image-processing-db
  db: postgres

rabbit:
  host: rabbitmq
  port: 5672
  user: user
  password: password
  routing_key: image-processing
  queue_name: image-processing
